name: logging_service
description: "Dio üçün şəbəkə log/debug aləti — sürüklənən FAB, log siyahısı, detal, statistika və kopyalama formatları."
version: 0.1.0

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  json_view: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
